name: PHP CD
on:
  workflow_run:
    workflows: ["PHP CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Get latest release
      uses: actions/github-script@v7
      id: get-latest-release
      with:
        script: |
          const release = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          return release.data.assets[0].url;

    - name: Download release asset
      run: |
        curl -L -H "Accept: application/octet-stream" -o php_app.zip "${{ steps.get-latest-release.outputs.result }}"
        
    - name: Verify download
      run: |
        dir php_app.zip